<a href="https://colab.research.google.com/github/sawthi-29/datasciencelearing/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

In [3]:
import numpy as np
l = [1,2,3,4,5]
print(l)
print("type of list",type(l))
#after converting into list
l = np.array(l)
print(l)
print("type of array",type(l))
print(l.ndim)

[1, 2, 3, 4, 5]
type of list <class 'list'>
[1 2 3 4 5]
type of array <class 'numpy.ndarray'>
1


In [4]:
#creating 2d arrays
l1 = [1,2,3,4,5]
l2 = [3,4,5,6,7]
l3 = [5,6,7,8,9]
l4 = np.array([
    l1,
    l2,
    l3
])
print(l4)
print(l4.ndim)

[[1 2 3 4 5]
 [3 4 5 6 7]
 [5 6 7 8 9]]
2


In [6]:
#different ways to create arrays in numpy

In [7]:
#using array
l = [1,2,3,4,5]
p = (1,2,3,4,5)
l = np.array(l)
p = np.array(p)
print("list converted into array")
print(l)
print("tuple converted into array")
print(p)

list converted into array
[1 2 3 4 5]
tuple converted into array
[1 2 3 4 5]


In [9]:
# fromiter/
l = [1,2,3,4,5]
arr = np.fromiter(l, dtype=int)
print(arr)

[1 2 3 4 5]


In [10]:
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
arr = np.array([[1,2,3,4,5],[4,5,6,7,8]])
print(arr)
print(arr.sum(axis=0))
print(arr.sum(axis=1))

[[1 2 3 4 5]
 [4 5 6 7 8]]
[ 5  7  9 11 13]
[15 30]


In [16]:
# indexing
l = [10,20,30,40]
arr = np.array(1)
print(arr[3])
print(arr[0])
print(arr[1])
print(arr[-1])



IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [19]:
l2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(l2)
print(l2[0,0])
print(l2[2,2])
print(l2[1,0])
print(l2[0])
print(l2[1])
print(l2[2])
print(l2[:,0])
print(l2[:,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
9
4
[1 2 3]
[4 5 6]
[7 8 9]
[1 4 7]
[2 5 8]
